version: "3.8"

services:
  server:
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:rainbow-api.danielmesquitta.com"
    build: .
    ports:
      - "8080:8080"
    command: npm start

  reverse-proxy:
    image: traefik
    command: --api --docker.exposedbydefault=false
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
