name: Docker Image CD

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  build:
    name: Executing remote ssh commands
    runs-on: ubuntu-latest

    steps:
      - name: "1. Pull Docker image from DockerHub; 2. Kill process in port 80; 3. Delete old docker container; 4. Run docker container"
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          key: ${{ secrets.EC2_SSH_KEY }}
          username: ${{ secrets.EC2_USER }}
          script: |
            cd /home/${{ secrets.EC2_USER }}
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/rainbow-server:latest
            sudo kill -9 $(sudo lsof -t -i:80) || true
            sudo docker rm -f rainbow-server-container || true
            sudo docker run -d -p 80:80 --name rainbow-server-container ${{ secrets.DOCKERHUB_USERNAME }}/rainbow-server -e DATABASE_URL=${{ secrets.DATABASE_URL }}
