name: Docker Image CI

on:
  push:
    branches: ["main"]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  DOCKER_IMAGE: rainbow-server

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN

      - name: Build the Docker image
        run: docker build -t $DOCKER_IMAGE .

      - name: Push the Docker image to DockerHub
        run: docker push $DOCKERHUB_USERNAME/$DOCKER_IMAGE:latest
