name: Server CI and CD

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: Executing remote ssh commands
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v3

      - name: SSH to EC2 instance and execute commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          key: ${{ secrets.EC2_SSH_KEY }}
          username: ${{ secrets.EC2_USER }}
          script: |
            cd /home/${{ secrets.EC2_USER }}
            git clone https://github.com/danielmesquitta/rainbow || true
            cd rainbow
            git pull
            echo '${{ secrets.ENV }}' > .env
            echo '${{ secrets.SSL_CERTIFICATE }}' > certificate.crt
            echo '${{ secrets.SSL_PRIVATE_KEY }}' > private.key
            sudo kill -9 $(sudo lsof -t -i:80) || true
            docker stop $(docker ps -aq) || true
            docker rmi $(docker images -q) -f || true
            docker rm $(docker ps -aq) -f || true
            docker compose -f docker-compose.yml up -d
            docker exec rainbow-server-1 bash -c "npm run db:deploy"
