name: Docker Image CD

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  DOCKER_IMAGE: rainbow-server

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker image from DockerHub
        run: sudo docker pull $DOCKERHUB_USERNAME/$DOCKER_IMAGE:latest

      - name: Delete old docker container
        run: sudo docker rm -f $DOCKER_IMAGE-container || true

      - name: Run docker container
        run: sudo docker run -d -p 8080:8080 --name $DOCKER_IMAGE-container $DOCKERHUB_USERNAME/$DOCKER_IMAGE -e DATABASE_URL=$DATABASE_URL
